import { registerComponents } from "@elfui/core";

import { installUtilityStyles } from "./utilities";

import {
  Avatar,
  AvatarGroup,
  Badge,
  Button,
  Icon,
  Link,
  Quote,
  Tag,
  Text,
} from "./components/Basic/index";
import {
  Card,
  Carousel,
  CarouselItem,
  Collapse,
  Countdown,
  Descriptions,
  DescriptionsItem,
  Divider,
  Empty,
  Image,
  InfiniteScroll,
  List,
  ListItem,
  Parallax,
  Pagination,
  Progress,
  Result,
  Skeleton,
  Sparkline,
  Statistic,
  Table,
  TableV2,
  Timeline,
  Transfer,
  Tree,
  VirtualList,
  Watermark,
} from "./components/Data/index";
import { CollapseItem } from "./components/Data/CollapseItem/index";
import { Message as MessageElement } from "./components/Feedback/Message/component";
import { MessageBox as MessageBoxElement } from "./components/Feedback/MessageBox/component";
import { Notification as NotificationElement } from "./components/Feedback/Notification/component";
import {
  Alert,
  Dialog,
  Drawer,
  Loading,
  PopConfirm,
  Tooltip,
  Tour,
} from "./components/Feedback/index";
import {
  Autocomplete,
  Cascader,
  CascaderPanel,
  Checkbox,
  CheckboxGroup,
  Form,
  FormItem,
  Input,
  InputNumber,
  InputOtp,
  InputTag,
  Mention,
  Radio,
  RadioGroup,
  Rate,
  Segmented,
  Select,
  Slider,
  Switch,
  Textarea,
  TreeSelect,
  Upload,
} from "./components/Form/index";
import {
  AiApprovalCard,
  AiChat,
  AiCodeBlock,
  AiCommandSearch,
  AiContextCard,
  AiDiffTable,
  AiFilterTable,
  AiFineTuneCard,
  AiInsightCard,
  AiLoading,
  AiRecommendationCard,
  AiRecordsTable,
  AiSidebarNav,
  AiStreamingText,
  AiTaskRow,
  AiThinking,
  AiToolChips,
  ChatComposer,
  ChatMessage,
  ChatToolCall,
  CodeCard,
  Heatmap,
  MdOutline,
  MdPage,
  Video,
} from "./components/Labs/index";
import {
  Aside,
  Container,
  Flex,
  Footer,
  Grid,
  GridItem,
  Header,
  Layout,
  Main,
  Masonry,
  Scrollbar,
  Space,
  Spacer,
  Splitter,
  SplitterPanel,
  Sticky,
  Toolbar,
} from "./components/Layout/index";
import {
  Anchor,
  AnchorLink,
  AppBar,
  BackTop,
  BottomNavigation,
  Breadcrumb,
  Dropdown,
  DropdownMenu,
  Menu,
  MenuItemGroup,
  PageHeader,
  Step,
  Steps,
  SubMenu,
  TabPane,
  Tabs,
} from "./components/Navigation/index";
import { BreadcrumbItem } from "./components/Navigation/BreadcrumbItem/index";
import { DropdownItem } from "./components/Navigation/DropdownItem/index";
import { MenuItem } from "./components/Navigation/MenuItem/index";
import {
  Calendar,
  ColorPicker,
  DatePicker,
  DateTimePicker,
  TimePicker,
  TimeSelect,
} from "./components/Picker/index";
import {
  ConfigProvider,
  DefaultsProvider,
  IconProvider,
  LocaleProvider,
  ThemeProvider,
} from "./components/Providers/index";

export const ALL_COMPONENTS: readonly CustomElementConstructor[] = [
  Avatar,
  AvatarGroup,
  Badge,
  Button,
  Icon,
  Link,
  Quote,
  Tag,
  Text,
  Card,
  Carousel,
  CarouselItem,
  Collapse,
  CollapseItem,
  Countdown,
  Descriptions,
  DescriptionsItem,
  Divider,
  Empty,
  Image,
  InfiniteScroll,
  List,
  ListItem,
  Parallax,
  Pagination,
  Progress,
  Result,
  Skeleton,
  Sparkline,
  Statistic,
  Table,
  TableV2,
  Timeline,
  Transfer,
  Tree,
  VirtualList,
  Watermark,
  Alert,
  Dialog,
  Drawer,
  Loading,
  MessageElement,
  MessageBoxElement,
  NotificationElement,
  PopConfirm,
  Tooltip,
  Tour,
  Autocomplete,
  Cascader,
  CascaderPanel,
  Checkbox,
  CheckboxGroup,
  Form,
  FormItem,
  Input,
  InputNumber,
  InputOtp,
  InputTag,
  Mention,
  Radio,
  RadioGroup,
  Rate,
  Segmented,
  Select,
  Slider,
  Switch,
  Textarea,
  TreeSelect,
  Upload,
  Aside,
  Container,
  Flex,
  Footer,
  Grid,
  GridItem,
  Header,
  Layout,
  Main,
  Masonry,
  Scrollbar,
  Space,
  Spacer,
  Splitter,
  SplitterPanel,
  Sticky,
  Toolbar,
  Anchor,
  AnchorLink,
  AppBar,
  BackTop,
  BottomNavigation,
  Breadcrumb,
  BreadcrumbItem,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  Menu,
  MenuItem,
  MenuItemGroup,
  PageHeader,
  Step,
  Steps,
  SubMenu,
  TabPane,
  Tabs,
  Calendar,
  ColorPicker,
  DatePicker,
  DateTimePicker,
  TimePicker,
  TimeSelect,
  ConfigProvider,
  DefaultsProvider,
  IconProvider,
  LocaleProvider,
  ThemeProvider,
  AiApprovalCard,
  AiChat,
  AiCodeBlock,
  AiCommandSearch,
  AiContextCard,
  AiDiffTable,
  AiFilterTable,
  AiFineTuneCard,
  AiInsightCard,
  AiLoading,
  AiRecommendationCard,
  AiRecordsTable,
  AiSidebarNav,
  AiStreamingText,
  AiTaskRow,
  AiThinking,
  AiToolChips,
  ChatComposer,
  ChatMessage,
  ChatToolCall,
  CodeCard,
  Heatmap,
  MdOutline,
  MdPage,
  Video,
];

const styledDocuments = new WeakSet<Document>();

const installDefaultStyles = (): void => {
  if (typeof document === "undefined" || styledDocuments.has(document)) return;
  installUtilityStyles(document);
  styledDocuments.add(document);
};

/** Registers every stable, AI, and Labs custom element and installs its global tokens. */
export const registerAllComponents = (): void => {
  installDefaultStyles();
  registerComponents(...ALL_COMPONENTS);
};
