// cspell:ignore sparkline

import {
  mdiAccountCircleOutline,
  mdiAlertOutline,
  mdiAnchor,
  mdiArrowUpBoldCircleOutline,
  mdiAt,
  mdiBadgeAccountOutline,
  mdiBellOutline,
  mdiBlur,
  mdiBookOpenPageVariantOutline,
  mdiButtonPointer,
  mdiCalendar,
  mdiCalendarClock,
  mdiCalendarMonthOutline,
  mdiCardOutline,
  mdiCardTextOutline,
  mdiChartBoxOutline,
  mdiChartLine,
  mdiCheckCircleOutline,
  mdiCheckboxMarkedOutline,
  mdiChevronRightBoxOutline,
  mdiCircleOpacity,
  mdiClockCheckOutline,
  mdiClockOutline,
  mdiCloudUploadOutline,
  mdiCodeBraces,
  mdiCodeTags,
  mdiCogOutline,
  mdiCursorDefaultClickOutline,
  mdiCursorPointer,
  mdiDatabaseOutline,
  mdiDockBottom,
  mdiDockRight,
  mdiDockTop,
  mdiEmoticonOutline,
  mdiFileTreeOutline,
  mdiFlaskOutline,
  mdiFormDropdown,
  mdiFormatListBulleted,
  mdiFormatQuoteClose,
  mdiFormatText,
  mdiFormSelect,
  mdiFormTextbox,
  mdiFrequentlyAskedQuestions,
  mdiGestureTap,
  mdiGestureTapButton,
  mdiGrid,
  mdiHammerWrench,
  mdiHuman,
  mdiImageOutline,
  mdiInboxOutline,
  mdiInfinity,
  mdiLinkVariant,
  mdiLoading,
  mdiMapMarkerPath,
  mdiMenu,
  mdiMenuDown,
  mdiMessageAlertOutline,
  mdiMessageQuestionOutline,
  mdiMessageTextOutline,
  mdiMinus,
  mdiMotion,
  mdiMouseMoveDown,
  mdiNavigationVariantOutline,
  mdiNumeric,
  mdiPackageDown,
  mdiPageLayoutBody,
  mdiPageLayoutFooter,
  mdiPageLayoutHeader,
  mdiPageNextOutline,
  mdiPaletteOutline,
  mdiPanVertical,
  mdiPinOutline,
  mdiPlayBoxOutline,
  mdiProgressClock,
  mdiRadioboxMarked,
  mdiResize,
  mdiRocketLaunchOutline,
  mdiSetCenter,
  mdiShapeOutline,
  mdiShieldKeyOutline,
  mdiSourceBranch,
  mdiStairs,
  mdiStarOutline,
  mdiSwapHorizontal,
  mdiTab,
  mdiTable,
  mdiTableLarge,
  mdiTagOutline,
  mdiTagPlusOutline,
  mdiTextLong,
  mdiTextSearch,
  mdiThemeLightDark,
  mdiTimelineClockOutline,
  mdiToggleSwitchOutline,
  mdiTools,
  mdiTooltipOutline,
  mdiTooltipTextOutline,
  mdiTranslate,
  mdiTuneVariant,
  mdiUnfoldMoreHorizontal,
  mdiUpdate,
  mdiViewCarouselOutline,
  mdiViewColumnOutline,
  mdiViewDashboardOutline,
  mdiViewDashboardVariantOutline,
  mdiViewGridOutline,
  mdiViewListOutline,
  mdiViewQuiltOutline,
  mdiViewSplitVertical,
  mdiViewWeekOutline,
  mdiWatermark,
  mdiWeb,
} from "@mdi/js";

const GROUP_ICONS: Readonly<Record<string, string>> = {
  Getting: mdiRocketLaunchOutline,
  Guide: mdiBookOpenPageVariantOutline,
  Layout: mdiViewDashboardOutline,
  Basic: mdiShapeOutline,
  Form: mdiFormTextbox,
  Feedback: mdiMessageAlertOutline,
  Data: mdiDatabaseOutline,
  Navigation: mdiNavigationVariantOutline,
  Picker: mdiCursorPointer,
  Directives: mdiGestureTapButton,
  Labs: mdiFlaskOutline,
};

const ROUTE_ICONS: Readonly<Record<string, string>> = {
  "/overview": mdiViewGridOutline,
  "/getting-started/installation": mdiPackageDown,
  "/getting-started/upgrade-guide": mdiUpdate,
  "/getting-started/browser-support": mdiWeb,
  "/getting-started/faq": mdiFrequentlyAskedQuestions,
  "/providers/config": mdiCogOutline,
  "/providers/theme": mdiThemeLightDark,
  "/theme-studio": mdiPaletteOutline,
  "/basic/icon": mdiEmoticonOutline,
  "/providers/locale": mdiTranslate,
  "/guide/accessibility": mdiHuman,
  "/guide/build": mdiHammerWrench,
  "/utilities": mdiTools,
  "/layout/grid": mdiGrid,
  "/layout/flex": mdiViewColumnOutline,
  "/layout/shell": mdiPageLayoutBody,
  "/layout/sticky": mdiPinOutline,
  "/layout/splitter": mdiViewSplitVertical,
  "/layout/scrollbar": mdiPanVertical,
  "/layout/masonry": mdiViewDashboardVariantOutline,
  "/layout/toolbar": mdiDockTop,
  "/basic/button": mdiButtonPointer,
  "/basic/link": mdiLinkVariant,
  "/basic/text": mdiFormatText,
  "/basic/quote": mdiFormatQuoteClose,
  "/basic/tag": mdiTagOutline,
  "/basic/badge": mdiBadgeAccountOutline,
  "/basic/avatar": mdiAccountCircleOutline,
  "/form/input": mdiFormTextbox,
  "/form/input-otp": mdiShieldKeyOutline,
  "/form/input-tag": mdiTagPlusOutline,
  "/form/autocomplete": mdiTextSearch,
  "/form/mention": mdiAt,
  "/form/input-number": mdiNumeric,
  "/form/textarea": mdiTextLong,
  "/form/switch": mdiToggleSwitchOutline,
  "/form/checkbox": mdiCheckboxMarkedOutline,
  "/form/radio": mdiRadioboxMarked,
  "/form/select": mdiFormDropdown,
  "/form/tree-select": mdiFileTreeOutline,
  "/form/segmented": mdiViewWeekOutline,
  "/form/cascader": mdiSourceBranch,
  "/form/form": mdiFormSelect,
  "/form/upload": mdiCloudUploadOutline,
  "/form/rate": mdiStarOutline,
  "/form/slider": mdiTuneVariant,
  "/feedback/alert": mdiAlertOutline,
  "/feedback/loading": mdiLoading,
  "/feedback/message": mdiMessageTextOutline,
  "/feedback/message-box": mdiMessageAlertOutline,
  "/feedback/dialog": mdiCardTextOutline,
  "/feedback/drawer": mdiDockRight,
  "/feedback/notification": mdiBellOutline,
  "/feedback/tooltip": mdiTooltipTextOutline,
  "/feedback/pop-confirm": mdiMessageQuestionOutline,
  "/feedback/tour": mdiMapMarkerPath,
  "/data/divider": mdiMinus,
  "/data/empty": mdiInboxOutline,
  "/data/result": mdiCheckCircleOutline,
  "/data/collapse": mdiUnfoldMoreHorizontal,
  "/data/descriptions": mdiFormatListBulleted,
  "/data/statistic": mdiChartBoxOutline,
  "/data/watermark": mdiWatermark,
  "/data/infinite-scroll": mdiInfinity,
  "/data/image": mdiImageOutline,
  "/data/sparkline": mdiChartLine,
  "/data/parallax": mdiMotion,
  "/data/transfer": mdiSwapHorizontal,
  "/data/card": mdiCardOutline,
  "/data/pagination": mdiPageNextOutline,
  "/data/progress": mdiProgressClock,
  "/data/table": mdiTable,
  "/data/virtual-table": mdiTableLarge,
  "/data/list": mdiFormatListBulleted,
  "/data/virtual-list": mdiViewListOutline,
  "/data/skeleton": mdiViewQuiltOutline,
  "/data/carousel": mdiViewCarouselOutline,
  "/data/timeline": mdiTimelineClockOutline,
  "/data/tree": mdiFileTreeOutline,
  "/navigation/anchor": mdiAnchor,
  "/navigation/backtop": mdiArrowUpBoldCircleOutline,
  "/navigation/breadcrumb": mdiChevronRightBoxOutline,
  "/navigation/dropdown": mdiMenuDown,
  "/navigation/menu": mdiMenu,
  "/navigation/tabs": mdiTab,
  "/navigation/steps": mdiStairs,
  "/navigation/page-header": mdiPageLayoutHeader,
  "/navigation/app-bar": mdiDockTop,
  "/navigation/bottom-navigation": mdiDockBottom,
  "/navigation/footer": mdiPageLayoutFooter,
  "/picker/color": mdiPaletteOutline,
  "/picker/date": mdiCalendar,
  "/picker/date-time": mdiCalendarClock,
  "/picker/time": mdiClockOutline,
  "/picker/time-select": mdiClockCheckOutline,
  "/picker/calendar": mdiCalendarMonthOutline,
  "/directives/click-outside": mdiCursorDefaultClickOutline,
  "/directives/intersect": mdiSetCenter,
  "/directives/mutate": mdiCodeBraces,
  "/directives/resize": mdiResize,
  "/directives/ripple": mdiCircleOpacity,
  "/directives/scroll": mdiMouseMoveDown,
  "/directives/tooltip": mdiTooltipOutline,
  "/directives/touch": mdiGestureTap,
  "/labs/video": mdiPlayBoxOutline,
  "/labs/heatmap": mdiBlur,
  "/labs/code-card": mdiCodeTags,
};

/** Resolves the semantic Material Design icon path for an app navigation entry. */
export const resolveAppMenuIcon = (index: string): string => {
  if (!index.startsWith("group:")) return ROUTE_ICONS[index] || mdiShapeOutline;
  const groupKey = index.slice("group:".length).split(/\s+/u)[0] || "";
  return GROUP_ICONS[groupKey] || mdiShapeOutline;
};

export const appMenuIconRoutes = Object.freeze(Object.keys(ROUTE_ICONS));
