// 由 scripts/generate-tag-types.mjs 自动生成 — 不要手改
//
// 引入本文件（或在用户项目 tsconfig 中 include）即可让
//   document.createElement("elf-button")
// 拿到完整 prop 类型。

declare global {
  interface HTMLElementTagNameMap {
    "elf-alert": HTMLElement & {
      type: string;
      variant: string;
      title: string;
      description: string;
      closable: boolean;
      showIcon: boolean;
      center: boolean;
    };
    "elf-anchor": HTMLElement & {
      items: unknown[];
      modelValue: string;
      defaultActive: string;
      container: unknown;
      offset: number;
      bounds: number;
      smooth: boolean;
      props: Record<string, unknown>;
      scrollToAnchor: (...args: unknown[]) => void;
    };
    "elf-aside": HTMLElement & {
      width: string;
    };
    "elf-autocomplete": HTMLElement & {
      modelValue: string;
      options: unknown[];
      fetchSuggestions: unknown;
      placeholder: string;
      disabled: boolean;
      clearable: boolean;
      triggerOnFocus: boolean;
    };
    "elf-avatar": HTMLElement & {
      size: string;
      shape: string;
      src: string;
      alt: string;
      icon: string;
      color: string;
    };
    "elf-back-top": HTMLElement & {
      target: unknown;
      visibilityHeight: number;
      right: unknown;
      bottom: unknown;
      zIndex: unknown;
      smooth: boolean;
      shape: string;
      size: unknown;
      icon: string;
      disabled: boolean;
      scrollToTop: (...args: unknown[]) => void;
    };
    "elf-badge": HTMLElement & {
      value: string;
      max: number;
      isDot: boolean;
      hidden: boolean;
      type: string;
      showZero: boolean;
      color: string;
    };
    "elf-breadcrumb": HTMLElement & {
      items: unknown[];
      separator: string;
      router: boolean;
      currentPath: string;
      maxItems: number;
      props: Record<string, unknown>;
    };
    "elf-button": HTMLElement & {
      variant: string;
      color: string;
      size: string;
      shape: string;
      disabled: boolean;
      loading: boolean;
      block: boolean;
      plain: boolean;
      dashed: boolean;
      autofocus: boolean;
      type: string;
      form: string;
    };
    "elf-calendar": HTMLElement & {
      modelValue: string;
      firstDayOfWeek: number;
    };
    "elf-card": HTMLElement & {
      variant: string;
      avatar: string;
      title: string;
      subtitle: string;
      image: string;
      imagePlacement: string;
      imageHeight: string;
      imageWidth: string;
      overlay: string;
      clickable: boolean;
    };
    "elf-carousel": HTMLElement & {
      effect: string;
      autoplay: boolean;
      interval: number;
      loop: boolean;
      showArrow: string;
      showIndicator: boolean;
      indicatorType: string;
      height: string;
      duration: string;
      pauseOnHover: boolean;
      radius: string;
    };
    "elf-cascader": HTMLElement & {
      modelValue: unknown[];
      options: unknown[];
      size: string;
      placeholder: string;
      disabled: boolean;
      clearable: boolean;
      multiple: boolean;
      checkable: boolean;
      separator: string;
      showAllLevels: boolean;
      collapseTags: boolean;
      collapseTagsTooltip: boolean;
      maxCollapseTags: number;
      maxCollapseTagsTooltipHeight: unknown;
      checkStrictly: boolean;
      emitPath: boolean;
      expandTrigger: string;
      checkOnClickNode: boolean;
      checkOnClickLeaf: boolean;
      showPrefix: boolean;
      showCheckedStrategy: string;
      filterable: boolean;
      debounce: number;
      virtualScroll: boolean;
      itemSize: number;
      height: number;
      props: Record<string, unknown>;
      clear: (...args: unknown[]) => void;
      open: (...args: unknown[]) => void;
      close: (...args: unknown[]) => void;
      togglePopperVisible: (...args: unknown[]) => void;
      getCheckedNodes: (...args: unknown[]) => CascaderNodeSnapshot[];
      presentText: (...args: unknown[]) => string;
    };
    "elf-checkbox": HTMLElement & {
      modelValue: unknown;
      value: unknown;
      label: string;
      disabled: boolean;
      size: string;
      indeterminate: boolean;
    };
    "elf-checkbox-group": HTMLElement & {
      modelValue: unknown[];
      disabled: boolean;
      size: string;
      min: number;
      max: number;
    };
    "elf-collapse": HTMLElement & {
      modelValue: unknown;
      accordion: boolean;
      items: unknown[];
      props: Record<string, unknown>;
    };
    "elf-color-picker": HTMLElement & {
      modelValue: string;
      format: string;
      presets: unknown[];
      showAlpha: boolean;
      disabled: boolean;
      clearable: boolean;
    };
    "elf-container": HTMLElement & {
      maxWidth: string;
      padding: string;
    };
    "elf-date-picker": HTMLElement & {
      modelValue: unknown;
      endValue: string;
      type: string;
      range: boolean;
      multiple: boolean;
      actions: boolean;
      showHeader: boolean;
      header: string;
      min: string;
      max: string;
      placeholder: string;
      endPlaceholder: string;
      disabled: boolean;
      clearable: boolean;
      shortcuts: unknown[];
      confirmText: string;
      cancelText: string;
      clearText: string;
    };
    "elf-defaults-provider": HTMLElement & {
      defaults: Record<string, unknown>;
      disabled: boolean;
      deep: boolean;
      strategy: string;
    };
    "elf-descriptions": HTMLElement & {
      title: string;
      extra: string;
      items: unknown[];
      column: number;
      border: boolean;
      direction: string;
      size: string;
      props: Record<string, unknown>;
    };
    "elf-dialog": HTMLElement & {
      title: string;
      size: string;
      closeOnMask: boolean;
      closeOnEscape: boolean;
      closable: boolean;
      lockScroll: boolean;
      beforeClose: unknown;
      close: (...args: unknown[]) => void;
    };
    "elf-divider": HTMLElement & {
      direction: string;
      contentPosition: string;
      dashed: boolean;
    };
    "elf-drawer": HTMLElement & {
      title: string;
      direction: string;
      size: string;
      modal: boolean;
      closeOnMask: boolean;
      closeOnEscape: boolean;
      closable: boolean;
      lockScroll: boolean;
      beforeClose: unknown;
      close: (...args: unknown[]) => void;
    };
    "elf-dropdown": HTMLElement & {
      items: unknown[];
      label: string;
      trigger: string;
      placement: string;
      size: string;
      disabled: boolean;
      hideOnClick: boolean;
      splitButton: boolean;
      maxHeight: string;
      props: Record<string, unknown>;
      show: (...args: unknown[]) => void;
      hide: (...args: unknown[]) => void;
      toggle: (...args: unknown[]) => void;
    };
    "elf-flex": HTMLElement & {
      direction: string;
      justify: string;
      align: string;
      gap: string;
      wrap: boolean;
    };
    "elf-footer": HTMLElement & {
      height: string;
    };
    "elf-form": HTMLElement & {
      model: Record<string, unknown>;
      rules: Record<string, unknown>;
      size: string;
      disabled: boolean;
      labelPosition: string;
      labelWidth: string;
      inline: boolean;
      hideRequiredAsterisk: boolean;
      validateOnRuleChange: boolean;
      scrollToError: boolean;
      validate: (...args: unknown[]) => Promise<boolean>;
      validateField: (...args: unknown[]) => Promise<boolean>;
      resetFields: (...args: unknown[]) => void;
      clearValidate: (...args: unknown[]) => void;
    };
    "elf-form-item": HTMLElement & {
      prop: string;
      label: string;
      rules: unknown[];
      required: boolean;
      size: string;
      error: string;
      inlineMessage: boolean;
      showMessage: boolean;
    };
    "elf-grid": HTMLElement & {
      columns: number;
      gap: string;
    };
    "elf-grid-item": HTMLElement & {
      span: number;
    };
    "elf-header": HTMLElement & {
      height: string;
    };
    "elf-image": HTMLElement & {
      src: string;
      alt: string;
      fit: string;
      lazy: boolean;
    };
    "elf-infinite-scroll": HTMLElement & {
      disabled: boolean;
      distance: number;
      immediate: boolean;
      loading: boolean;
    };
    "elf-input": HTMLElement & {
      modelValue: unknown;
      modelModifiers: Record<string, unknown>;
      type: string;
      size: string;
      placeholder: string;
      disabled: boolean;
      readonly: boolean;
      clearable: boolean;
      showPassword: boolean;
      maxlength: number;
      minlength: number;
      showWordLimit: boolean;
      wordLimitPosition: string;
      clearIcon: string;
      prefixIcon: string;
      suffixIcon: string;
      formatter: unknown;
      parser: unknown;
      autocomplete: string;
      max: unknown;
      min: unknown;
      step: unknown;
      autofocus: boolean;
      form: string;
      ariaLabel: string;
      tabindex: unknown;
      validateEvent: boolean;
      inputStyle: unknown;
      label: string;
      inputmode: string;
      countGraphemes: unknown;
      id: string;
      name: string;
      blur: (...args: unknown[]) => void;
      clear: (...args: unknown[]) => void;
      focus: (...args: unknown[]) => void;
      input: (...args: unknown[]) => HTMLInputElement | null;
      ref: (...args: unknown[]) => HTMLInputElement | null;
      resizeTextarea: (...args: unknown[]) => void;
      select: (...args: unknown[]) => void;
      textarea: (...args: unknown[]) => null;
      textareaStyle: (...args: unknown[]) => Record<string, never>;
      isComposing: unknown;
      passwordVisible: unknown;
    };
    "elf-input-number": HTMLElement & {
      modelValue: number;
      min: number;
      max: number;
      step: number;
      stepStrictly: boolean;
      precision: number;
      disabled: boolean;
      readonly: boolean;
      controls: boolean;
      controlsPosition: string;
      size: string;
      placeholder: string;
      name: string;
    };
    "elf-input-otp": HTMLElement & {
      modelValue: string;
      length: number;
      type: string;
      size: string;
      disabled: boolean;
      readonly: boolean;
      placeholder: string;
      separator: string;
    };
    "elf-input-tag": HTMLElement & {
      modelValue: unknown[];
      placeholder: string;
      disabled: boolean;
      readonly: boolean;
      clearable: boolean;
      max: number;
      size: string;
    };
    "elf-layout": HTMLElement & {
      direction: string;
    };
    "elf-loading": HTMLElement & {
      loading: boolean;
      text: string;
      fullscreen: boolean;
      background: string;
      closable: boolean;
    };
    "elf-locale-provider": HTMLElement & {
      name: string;
      dir: string;
      rtl: boolean;
      messages: Record<string, unknown>;
    };
    "elf-main": HTMLElement;
    "elf-mention": HTMLElement & {
      modelValue: string;
      options: unknown[];
      prefix: string;
      placeholder: string;
      disabled: boolean;
      rows: number;
    };
    "elf-menu": HTMLElement & {
      items: unknown[];
      modelValue: string;
      defaultActive: string;
      defaultOpeneds: unknown[];
      mode: string;
      theme: string;
      collapse: boolean;
      uniqueOpened: boolean;
      router: boolean;
      props: Record<string, unknown>;
      backgroundColor: string;
      textColor: string;
      activeTextColor: string;
      activeBackground: string;
      width: string;
      collapseWidth: string;
      indent: number;
      rounded: boolean;
      elevation: boolean;
      showToggle: boolean;
      togglePlacement: string;
      searchable: boolean;
      searchPlaceholder: string;
      trigger: string;
      open: unknown;
      close: unknown;
      select: unknown;
    };
    "elf-message": HTMLElement & {
      message: string;
      type: string;
      position: string;
      closable: boolean;
      close: (...args: unknown[]) => void;
      closing: unknown;
    };
    "elf-notification": HTMLElement & {
      titleText: string;
      message: string;
      type: string;
      position: string;
      closable: boolean;
      close: (...args: unknown[]) => void;
      closing: unknown;
    };
    "elf-pagination": HTMLElement & {
      total: number;
      currentPage: number;
      pageSize: number;
      pageSizes: unknown[];
      pagerCount: number;
      layout: string;
      background: boolean;
      small: boolean;
      disabled: boolean;
      hideOnSinglePage: boolean;
    };
    "elf-playground": HTMLElement & {
      title: string;
      code: string;
      script: string;
    };
    "elf-pop-confirm": HTMLElement & {
      title: string;
      content: string;
      confirmText: string;
      cancelText: string;
      placement: string;
      trigger: string;
      visible: boolean;
      width: string;
      disabled: boolean;
      closeOnEscape: boolean;
      closeOnClickOutside: boolean;
      show: (...args: unknown[]) => void;
      hide: (...args: unknown[]) => void;
      toggle: (...args: unknown[]) => void;
      isVisible: (...args: unknown[]) => unknown;
    };
    "elf-progress": HTMLElement & {
      value: number;
      max: number;
      variant: string;
      status: string;
      color: string;
      trackColor: string;
      height: string;
      size: number;
      strokeWidth: number;
      showText: boolean;
      textInside: boolean;
      striped: boolean;
      indeterminate: boolean;
      format: unknown;
    };
    "elf-props-table": HTMLElement & {
      title: string;
      rows: unknown[];
    };
    "elf-radio": HTMLElement & {
      modelValue: unknown;
      value: unknown;
      label: string;
      disabled: boolean;
      size: string;
      border: boolean;
    };
    "elf-radio-group": HTMLElement & {
      modelValue: unknown;
      disabled: boolean;
      size: string;
      variant: string;
      fill: string;
      textColor: string;
    };
    "elf-rate": HTMLElement & {
      modelValue: number;
      max: number;
      allowHalf: boolean;
      clearable: boolean;
      disabled: boolean;
      readonly: boolean;
      size: string;
      color: string;
      voidColor: string;
      disabledColor: string;
      character: string;
      voidCharacter: string;
      showText: boolean;
      showScore: boolean;
      scoreTemplate: string;
      texts: unknown[];
    };
    "elf-scrollbar": HTMLElement & {
      always: boolean;
      native: boolean;
    };
    "elf-segmented": HTMLElement & {
      options: unknown[];
      size: string;
      disabled: boolean;
      block: boolean;
      props: Record<string, unknown>;
    };
    "elf-select": HTMLElement & {
      modelValue: unknown;
      options: unknown[];
      props: Record<string, unknown>;
      size: string;
      placeholder: string;
      disabled: boolean;
      valueKey: string;
      clearable: boolean;
      multiple: boolean;
      collapseTags: boolean;
      maxCollapseTags: number;
      collapseTagsTooltip: boolean;
      multipleLimit: number;
      filterable: boolean;
      allowCreate: boolean;
      filterMethod: unknown;
      remote: boolean;
      remoteMethod: unknown;
      debounce: number;
      reserveKeyword: boolean;
      defaultFirstOption: boolean;
      automaticDropdown: boolean;
      loading: boolean;
      loadingText: string;
      noDataText: string;
      noMatchText: string;
      valueOnClear: unknown;
      emptyValues: unknown[];
      height: number;
      fitInputWidth: boolean;
      tabindex: unknown;
      id: string;
      name: string;
      open: (...args: unknown[]) => void;
      close: (...args: unknown[]) => void;
      toggle: (...args: unknown[]) => void;
      selectedLabel: (...args: unknown[]) => string | string[];
    };
    "elf-skeleton": HTMLElement & {
      variant: string;
      width: string;
      height: string;
      animated: boolean;
      count: number;
      gap: string;
    };
    "elf-slider": HTMLElement & {
      modelValue: unknown;
      min: number;
      max: number;
      step: number;
      range: boolean;
      disabled: boolean;
      readonly: boolean;
      vertical: boolean;
      showTooltip: boolean;
      showStops: boolean;
      segmented: boolean;
      showInput: boolean;
      marks: unknown;
      color: string;
      size: string;
      formatTooltip: unknown;
      clear: (...args: unknown[]) => void;
      setValue: (...args: unknown[]) => void;
    };
    "elf-steps": HTMLElement & {
      active: number;
      direction: string;
      items: unknown[];
      size: string;
      clickable: boolean;
      alternativeLabel: boolean;
      next: (...args: unknown[]) => void;
      prev: (...args: unknown[]) => void;
      setActive: (...args: unknown[]) => void;
    };
    "elf-sticky": HTMLElement & {
      top: unknown;
      bottom: unknown;
      zIndex: unknown;
      disabled: boolean;
    };
    "elf-switch": HTMLElement & {
      modelValue: boolean;
      disabled: boolean;
      size: string;
      activeText: string;
      inactiveText: string;
      label: string;
      labelPosition: string;
      beforeChange: unknown;
      loading: boolean;
      inset: boolean;
      flat: boolean;
      color: string;
      activeColor: string;
      inactiveColor: string;
    };
    "elf-table": HTMLElement & {
      data: unknown[];
      columns: unknown[];
      rowKey: string;
      stripe: boolean;
      border: boolean;
      hover: boolean;
      size: string;
      height: string;
      maxHeight: string;
      emptyText: string;
      loading: boolean;
      showHeader: boolean;
      stickyHeader: boolean;
      highlightCurrentRow: boolean;
      currentRowKey: string;
      selectedKeys: unknown[];
      defaultSelectedKeys: unknown[];
      expandedRowKeys: unknown[];
      defaultExpandedRowKeys: unknown[];
      expandFormatter: unknown;
      sortProp: string;
      sortOrder: string;
      clearSelection: (...args: unknown[]) => void;
      toggleRowSelection: (...args: unknown[]) => void;
      toggleRowExpansion: (...args: unknown[]) => void;
      getSelectionRows: (...args: unknown[]) => Record<string, unknown>[];
      setCurrentRow: (...args: unknown[]) => void;
      sort: (...args: unknown[]) => void;
      clearSort: (...args: unknown[]) => void;
      clearFilter: (...args: unknown[]) => void;
    };
    "elf-tabs": HTMLElement & {
      items: unknown[];
      modelValue: string;
      defaultValue: string;
      alignTabs: string;
      density: string;
      direction: string;
      color: string;
      grow: boolean;
      stacked: boolean;
      showPanels: boolean;
      hideSlider: boolean;
      transition: string;
      transitionDuration: number;
      props: Record<string, unknown>;
      select: (...args: unknown[]) => void;
    };
    "elf-tag": HTMLElement & {
      color: string;
      size: string;
      variant: string;
      closable: boolean;
      round: boolean;
      disabled: boolean;
    };
    "elf-textarea": HTMLElement & {
      modelValue: string;
      size: string;
      placeholder: string;
      disabled: boolean;
      readonly: boolean;
      maxlength: number;
      showCount: boolean;
      rows: number;
      autosize: unknown;
      resize: string;
    };
    "elf-theme-provider": HTMLElement & {
      theme: string;
      primary: string;
      secondary: string;
      success: string;
      warning: string;
      danger: string;
      info: string;
      background: string;
      surface: string;
      textColor: string;
      tokens: Record<string, unknown>;
    };
    "elf-time-picker": HTMLElement & {
      modelValue: unknown;
      endValue: string;
      range: boolean;
      isRange: boolean;
      min: string;
      max: string;
      step: number;
      readonly: boolean;
      editable: boolean;
      size: string;
      placeholder: string;
      startPlaceholder: string;
      endPlaceholder: string;
      rangeSeparator: string;
      disabled: boolean;
      clearable: boolean;
      id: unknown;
      name: string;
      tabindex: unknown;
      valueOnClear: unknown;
      emptyValues: unknown[];
      saveOnBlur: boolean;
      shortcuts: unknown[];
      focus: (...args: unknown[]) => void;
      blur: (...args: unknown[]) => void;
      handleOpen: (...args: unknown[]) => void;
      handleClose: (...args: unknown[]) => void;
    };
    "elf-timeline": HTMLElement & {
      items: unknown[];
      mode: string;
      reverse: boolean;
    };
    "elf-tooltip": HTMLElement & {
      content: string;
      placement: string;
      disabled: boolean;
      trigger: string;
      showAfter: number;
      hideAfter: number;
      effect: string;
      visible: boolean;
      show: (...args: unknown[]) => void;
      hide: (...args: unknown[]) => void;
      isVisible: (...args: unknown[]) => unknown;
    };
    "elf-tour": HTMLElement & {
      steps: unknown[];
      visible: boolean;
      current: number;
      maskClosable: boolean;
      keyboard: boolean;
      lockScroll: boolean;
      gap: number;
      zIndex: number;
      prev: (...args: unknown[]) => void;
      next: (...args: unknown[]) => void;
      skip: (...args: unknown[]) => void;
      finish: (...args: unknown[]) => void;
      close: (...args: unknown[]) => void;
      open: (...args: unknown[]) => void;
    };
    "elf-transfer": HTMLElement & {
      data: unknown[];
      modelValue: unknown[];
      titles: unknown[];
      filterable: boolean;
      filterPlaceholder: string;
      props: Record<string, unknown>;
    };
    "elf-tree": HTMLElement & {
      data: unknown[];
      nodeKey: string;
      modelValue: string;
      currentNodeKey: string;
      defaultSelectedKey: string;
      defaultExpandedKeys: unknown[];
      defaultCheckedKeys: unknown[];
      expandedKeys: unknown[];
      checkedKeys: unknown[];
      props: Record<string, unknown>;
      showCheckbox: boolean;
      checkStrictly: boolean;
      highlightCurrent: boolean;
      accordion: boolean;
      defaultExpandAll: boolean;
      expandOnClickNode: boolean;
      checkOnClickNode: boolean;
      filterable: boolean;
      filterPlaceholder: string;
      emptyText: string;
      indent: number;
      expand: (...args: unknown[]) => void;
      collapse: (...args: unknown[]) => void;
      toggle: (...args: unknown[]) => void;
      select: (...args: unknown[]) => void;
      check: (...args: unknown[]) => void;
      uncheck: (...args: unknown[]) => void;
      setChecked: (...args: unknown[]) => void;
      setCheckedKeys: (...args: unknown[]) => void;
      setCheckedNodes: (...args: unknown[]) => void;
      getCheckedKeys: (...args: unknown[]) => string[];
      getCheckedNodes: (...args: unknown[]) => Record<string, unknown>[];
      getHalfCheckedKeys: (...args: unknown[]) => string[];
      getHalfCheckedNodes: (...args: unknown[]) => Record<string, unknown>[];
      setExpandedKeys: (...args: unknown[]) => void;
      getExpandedKeys: (...args: unknown[]) => string[];
      setCurrentKey: (...args: unknown[]) => void;
      setCurrentNode: (...args: unknown[]) => void;
      getCurrentKey: (...args: unknown[]) => string;
      getCurrentNode: (...args: unknown[]) => Record<string, unknown> | undefined;
      getNode: (...args: unknown[]) => Record<string, unknown> | undefined;
      filter: (...args: unknown[]) => void;
    };
    "elf-upload": HTMLElement & {
      modelValue: unknown[];
      action: string;
      method: string;
      headers: Record<string, unknown>;
      data: unknown;
      withCredentials: boolean;
      accept: string;
      crossorigin: string;
      name: string;
      multiple: boolean;
      directory: boolean;
      drag: boolean;
      disabled: boolean;
      autoUpload: boolean;
      limit: number;
      maxSize: number;
      fileNamePattern: string;
      chunkSize: number;
      listType: string;
      showFileList: boolean;
      buttonText: string;
      tip: string;
      beforeUpload: unknown;
      beforeRemove: unknown;
      customRequest: unknown;
      httpRequest: unknown;
      onPreview: unknown;
      onRemove: unknown;
      onSuccess: unknown;
      onError: unknown;
      onProgress: unknown;
      onChange: unknown;
      onExceed: unknown;
      chunkRequest: unknown;
      select: (...args: unknown[]) => void;
      submit: (...args: unknown[]) => void;
      clearFiles: (...args: unknown[]) => void;
      abort: (...args: unknown[]) => void;
      handleStart: (...args: unknown[]) => void;
      handleRemove: (...args: unknown[]) => void;
    };
  }
}

export {};
