// cspell:ignore sparkline

import {
  mdiAccountCircleOutline,
  mdiAlertOutline,
  mdiAnchor,
  mdiArrowUpBoldCircleOutline,
  mdiAt,
  mdiBadgeAccountOutline,
  mdiBellOutline,
  mdiBlur,
  mdiBookOpenPageVariantOutline,
  mdiBrain,
  mdiChatProcessingOutline,
  mdiCheckDecagramOutline,
  mdiClipboardCheckOutline,
  mdiButtonPointer,
  mdiCalendar,
  mdiCalendarClock,
  mdiCalendarMonthOutline,
  mdiCardOutline,
  mdiCardTextOutline,
  mdiChartBoxOutline,
  mdiChartLine,
  mdiCheckCircleOutline,
  mdiCheckboxMarkedOutline,
  mdiChevronRightBoxOutline,
  mdiCircleOpacity,
  mdiClockCheckOutline,
  mdiClockOutline,
  mdiCloudUploadOutline,
  mdiCodeBraces,
  mdiCodeTags,
  mdiCogOutline,
  mdiCursorDefaultClickOutline,
  mdiCursorPointer,
  mdiDatabaseOutline,
  mdiDockLeft,
  mdiDockBottom,
  mdiDockRight,
  mdiDockTop,
  mdiEmoticonOutline,
  mdiFileDocumentOutline,
  mdiFileTreeOutline,
  mdiFilterVariant,
  mdiFlaskOutline,
  mdiFormDropdown,
  mdiFormatListBulleted,
  mdiFormatQuoteClose,
  mdiFormatText,
  mdiFormSelect,
  mdiFormTextbox,
  mdiFormatHeaderIncrease,
  mdiFrequentlyAskedQuestions,
  mdiGestureTap,
  mdiGestureTapButton,
  mdiGrid,
  mdiHammerWrench,
  mdiHuman,
  mdiImageOutline,
  mdiInboxOutline,
  mdiInfinity,
  mdiLanguageMarkdown,
  mdiLinkVariant,
  mdiLoading,
  mdiMagnify,
  mdiMapMarkerPath,
  mdiMenu,
  mdiMenuDown,
  mdiMessageAlertOutline,
  mdiMessageQuestionOutline,
  mdiMessageTextOutline,
  mdiMinus,
  mdiMotion,
  mdiMouseMoveDown,
  mdiNavigationVariantOutline,
  mdiNumeric,
  mdiPackageDown,
  mdiPageLayoutBody,
  mdiPageLayoutFooter,
  mdiPageLayoutHeader,
  mdiPageNextOutline,
  mdiPaletteOutline,
  mdiPanVertical,
  mdiPinOutline,
  mdiPlayBoxOutline,
  mdiProgressClock,
  mdiRadioboxMarked,
  mdiResize,
  mdiRocketLaunchOutline,
  mdiRobot,
  mdiSendOutline,
  mdiSetCenter,
  mdiShapeOutline,
  mdiShieldKeyOutline,
  mdiSourceBranch,
  mdiStairs,
  mdiStarOutline,
  mdiSwapHorizontal,
  mdiTab,
  mdiTable,
  mdiTableLarge,
  mdiTagOutline,
  mdiTagPlusOutline,
  mdiTextLong,
  mdiTextBoxOutline,
  mdiTextSearch,
  mdiThemeLightDark,
  mdiThumbUpOutline,
  mdiTimelineClockOutline,
  mdiToolboxOutline,
  mdiToggleSwitchOutline,
  mdiTools,
  mdiTooltipOutline,
  mdiTooltipTextOutline,
  mdiTranslate,
  mdiTuneVariant,
  mdiUnfoldMoreHorizontal,
  mdiUpdate,
  mdiViewCarouselOutline,
  mdiViewColumnOutline,
  mdiViewDashboardOutline,
  mdiViewDashboardVariantOutline,
  mdiViewGridOutline,
  mdiViewListOutline,
  mdiViewQuiltOutline,
  mdiViewSplitVertical,
  mdiViewWeekOutline,
  mdiWatermark,
} from "@mdi/js";

const GROUP_ICONS: Readonly<Record<string, string>> = {
  Getting: mdiRocketLaunchOutline,
  Guide: mdiBookOpenPageVariantOutline,
  Layout: mdiViewDashboardOutline,
  Basic: mdiShapeOutline,
  Form: mdiFormTextbox,
  Feedback: mdiMessageAlertOutline,
  Data: mdiDatabaseOutline,
  Navigation: mdiNavigationVariantOutline,
  Picker: mdiCursorPointer,
  Directives: mdiGestureTapButton,
  Labs: mdiFlaskOutline,
  AI: mdiRobot,
};

const GROUP_ICON_COLORS: Readonly<Record<string, string>> = {
  Getting: "#1565C0",
  Guide: "#6A1B9A",
  Layout: "#00838F",
  Basic: "#F57F17",
  Form: "#2E7D32",
  Feedback: "#C62828",
  Data: "#0277BD",
  Navigation: "#4527A0",
  Picker: "#AD1457",
  Directives: "#EF6C00",
  Labs: "#37474F",
  AI: "#7C3AED",
};

const ROUTE_ICONS: Readonly<Record<string, string>> = {
  "/overview": mdiViewGridOutline,
  "/getting-started/installation": mdiPackageDown,
  "/getting-started/upgrade-guide": mdiUpdate,
  "/getting-started/faq": mdiFrequentlyAskedQuestions,
  "/providers/config": mdiCogOutline,
  "/providers/theme": mdiThemeLightDark,
  "/theme-studio": mdiPaletteOutline,
  "/basic/icon": mdiEmoticonOutline,
  "/basic/heading": mdiFormatHeaderIncrease,
  "/providers/locale": mdiTranslate,
  "/guide/accessibility": mdiHuman,
  "/guide/build": mdiHammerWrench,
  "/guide/markdown-page": mdiLanguageMarkdown,
  "/utilities": mdiTools,
  "/layout/grid": mdiGrid,
  "/layout/flex": mdiViewColumnOutline,
  "/layout/shell": mdiPageLayoutBody,
  "/layout/sticky": mdiPinOutline,
  "/layout/splitter": mdiViewSplitVertical,
  "/layout/scrollbar": mdiPanVertical,
  "/layout/masonry": mdiViewDashboardVariantOutline,
  "/layout/toolbar": mdiDockTop,
  "/basic/button": mdiButtonPointer,
  "/basic/link": mdiLinkVariant,
  "/basic/text": mdiFormatText,
  "/basic/quote": mdiFormatQuoteClose,
  "/basic/tag": mdiTagOutline,
  "/basic/badge": mdiBadgeAccountOutline,
  "/basic/avatar": mdiAccountCircleOutline,
  "/form/input": mdiFormTextbox,
  "/form/input-otp": mdiShieldKeyOutline,
  "/form/input-tag": mdiTagPlusOutline,
  "/form/autocomplete": mdiTextSearch,
  "/form/mention": mdiAt,
  "/form/input-number": mdiNumeric,
  "/form/textarea": mdiTextLong,
  "/form/switch": mdiToggleSwitchOutline,
  "/form/checkbox": mdiCheckboxMarkedOutline,
  "/form/radio": mdiRadioboxMarked,
  "/form/select": mdiFormDropdown,
  "/form/tree-select": mdiFileTreeOutline,
  "/form/segmented": mdiViewWeekOutline,
  "/form/cascader": mdiSourceBranch,
  "/form/form": mdiFormSelect,
  "/form/upload": mdiCloudUploadOutline,
  "/form/rate": mdiStarOutline,
  "/form/slider": mdiTuneVariant,
  "/feedback/alert": mdiAlertOutline,
  "/feedback/loading": mdiLoading,
  "/feedback/message": mdiMessageTextOutline,
  "/feedback/message-box": mdiMessageAlertOutline,
  "/feedback/dialog": mdiCardTextOutline,
  "/feedback/drawer": mdiDockRight,
  "/feedback/notification": mdiBellOutline,
  "/feedback/tooltip": mdiTooltipTextOutline,
  "/feedback/pop-confirm": mdiMessageQuestionOutline,
  "/feedback/tour": mdiMapMarkerPath,
  "/data/divider": mdiMinus,
  "/data/empty": mdiInboxOutline,
  "/data/result": mdiCheckCircleOutline,
  "/data/collapse": mdiUnfoldMoreHorizontal,
  "/data/descriptions": mdiFormatListBulleted,
  "/data/statistic": mdiChartBoxOutline,
  "/data/watermark": mdiWatermark,
  "/data/infinite-scroll": mdiInfinity,
  "/data/image": mdiImageOutline,
  "/data/sparkline": mdiChartLine,
  "/data/parallax": mdiMotion,
  "/data/transfer": mdiSwapHorizontal,
  "/data/card": mdiCardOutline,
  "/data/pagination": mdiPageNextOutline,
  "/data/progress": mdiProgressClock,
  "/data/table": mdiTable,
  "/data/virtual-table": mdiTableLarge,
  "/data/list": mdiFormatListBulleted,
  "/data/virtual-list": mdiViewListOutline,
  "/data/skeleton": mdiViewQuiltOutline,
  "/data/carousel": mdiViewCarouselOutline,
  "/data/timeline": mdiTimelineClockOutline,
  "/data/tree": mdiFileTreeOutline,
  "/navigation/anchor": mdiAnchor,
  "/navigation/backtop": mdiArrowUpBoldCircleOutline,
  "/navigation/breadcrumb": mdiChevronRightBoxOutline,
  "/navigation/dropdown": mdiMenuDown,
  "/navigation/menu": mdiMenu,
  "/navigation/tabs": mdiTab,
  "/navigation/steps": mdiStairs,
  "/navigation/page-header": mdiPageLayoutHeader,
  "/navigation/app-bar": mdiDockTop,
  "/navigation/bottom-navigation": mdiDockBottom,
  "/navigation/footer": mdiPageLayoutFooter,
  "/picker/color": mdiPaletteOutline,
  "/picker/date": mdiCalendar,
  "/picker/date-time": mdiCalendarClock,
  "/picker/time": mdiClockOutline,
  "/picker/time-select": mdiClockCheckOutline,
  "/picker/calendar": mdiCalendarMonthOutline,
  "/directives/click-outside": mdiCursorDefaultClickOutline,
  "/directives/intersect": mdiSetCenter,
  "/directives/mutate": mdiCodeBraces,
  "/directives/resize": mdiResize,
  "/directives/ripple": mdiCircleOpacity,
  "/directives/scroll": mdiMouseMoveDown,
  "/directives/tooltip": mdiTooltipOutline,
  "/directives/touch": mdiGestureTap,
  "/labs/video": mdiPlayBoxOutline,
  "/labs/heatmap": mdiBlur,
  "/labs/code-card": mdiCodeTags,
  "/labs/md-page": mdiLanguageMarkdown,
  "/labs/doc-sync": mdiDockLeft,
  "/labs/ai-chat": mdiChatProcessingOutline,
  "/labs/chat-message": mdiMessageTextOutline,
  "/labs/chat-tool-call": mdiToolboxOutline,
  "/labs/chat-composer": mdiSendOutline,
  "/labs/ai-loading": mdiLoading,
  "/labs/ai-thinking": mdiBrain,
  "/labs/ai-approval": mdiCheckDecagramOutline,
  "/labs/ai-task-row": mdiClipboardCheckOutline,
  "/labs/ai-context-card": mdiFileDocumentOutline,
  "/labs/ai-recommendation": mdiThumbUpOutline,
  "/labs/ai-command-search": mdiMagnify,
  "/labs/ai-code-block": mdiCodeBraces,
  "/labs/ai-streaming-text": mdiMessageTextOutline,
  "/labs/ai-tool-chips": mdiTextBoxOutline,
  "/labs/ai-diff-table": mdiTable,
  "/labs/ai-records-table": mdiTableLarge,
  "/labs/ai-filter-table": mdiFilterVariant,
  "/labs/ai-sidebar-nav": mdiViewDashboardOutline,
  "/labs/ai-insight-card": mdiChartBoxOutline,
  "/labs/ai-fine-tune-card": mdiTuneVariant,
  "/labs/ai-showcase": mdiViewDashboardVariantOutline,
};

/** Resolves the semantic Material Design icon path for an app navigation entry. */
export const resolveAppMenuIcon = (index: string): string => {
  if (!index.startsWith("group:")) return ROUTE_ICONS[index] || mdiShapeOutline;
  const groupKey = index.slice("group:".length).split(/\s+/u)[0] || "";
  return GROUP_ICONS[groupKey] || mdiShapeOutline;
};

/** Resolves a Material palette color for each app navigation group. */
export const resolveAppMenuIconColor = (index: string): string => {
  if (index.startsWith("group:")) {
    const groupKey = index.slice("group:".length).split(/\s+/u)[0] || "";
    return GROUP_ICON_COLORS[groupKey] || "#1565C0";
  }
  if (index.startsWith("/getting-started/") || index === "/overview") return "#1565C0";
  if (index.startsWith("/guide/") || index.startsWith("/providers/") || index === "/theme-studio") {
    return "#6A1B9A";
  }
  if (index.startsWith("/layout/") || index.startsWith("/utilities")) return "#00838F";
  if (index.startsWith("/basic/")) return "#F57F17";
  if (index.startsWith("/form/")) return "#2E7D32";
  if (index.startsWith("/feedback/")) return "#C62828";
  if (index.startsWith("/data/")) return "#0277BD";
  if (index.startsWith("/navigation/")) return "#4527A0";
  if (index.startsWith("/picker/")) return "#AD1457";
  if (index.startsWith("/directives/")) return "#EF6C00";
  if (index.startsWith("/labs/ai-") || index.startsWith("/labs/chat-")) return "#7C3AED";
  if (index.startsWith("/labs/")) return "#37474F";
  return "#1565C0";
};

export const appMenuIconRoutes = Object.freeze(Object.keys(ROUTE_ICONS));
